#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

import sys
import re
from termcolor import colored
import signal


def signal_handler(signal, frame):
    print('\nBye')
    sys.exit(0)
signal.signal(signal.SIGINT, signal_handler)


def format_time(time_array):
    time_string = '%s:' % str(time_array[0])
    if time_array[1] < 10:
        time_string += '0%d' % time_array[1]
    else:
        time_string += '%d' % time_array[1]
    return time_string


print('Please enter the times which you would like to add')

total_time = [0, 0]  # hours, minutes
while True:
    new_time_string = input('time> ')

    if re.match('re', new_time_string):
        total_time = [0, 0]
        print('reseted time')
        continue

    new_time = re.split(r'[:.]', new_time_string)

    if len(new_time) > 2:
        print('Please reenter your time (e.g. 7:45 or 7 meaning 7 hours). Could not parse it.')
        continue

    try:
        total_time[0] += int(new_time[0])
        if len(new_time) == 2:
            total_time[1] += int(new_time[1])

        if total_time[1] >= 60:
            total_time[0] += 1
            total_time[1] -= 60
    except:
        print('Please reenter your time (e.g. 7:45 or 7 meaning 7 hours). Could not parse it.')
        continue

    print('The count is: %s' % colored(format_time(total_time), 'green'))
