#!/bin/bash
## quick and dirty
if [ -z "$1" ]
then	echo "Please give me a ID from autoscout24.de"
	exit 1
fi

function work {
echo $1
id="$1"
filenametmpI="$$tmp1.pdf"
filenametmpII="$$tmp2.pdf"
LaTeXtmpfile="$id.tex"

if [ "$id" -lt 1 ]
then	echo "check your ID"
	exit 1
fi
if [ -e "$filename" ]
then	echo "$filename exists. Press enter to continue."
	read fnord
fi

url="http://www.autoscout24.de/PrintViewArticles.aspx?id=$id"
wkhtmltopdf "$url" "$filenametmpI"
pdfcrop --margins '0 -27 0 0' "$filenametmpI" "$filenametmpII" 
echo -n '\documentclass[a4paper]{scrartcl}\usepackage{pdfpages}\begin{document}\includepdf{' > "$LaTeXtmpfile"
echo -n "$filenametmpII" >> "$LaTeXtmpfile"
echo '}\end{document}' >> "$LaTeXtmpfile"
pdflatex -interaction=nonstopmode "$LaTeXtmpfile" >/dev/null
rm "$id.aux" "$id.log" "$id.tex" "$filenametmpI" "$filenametmpII"
}

while [ $# -gt 0 ]
do	work $1
	shift
done
