#!/usr/bin/perl

# SPDX-FileCopyrightText: 2012 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

use strict;
use warnings;
use autodie;
use feature qw(say);
use Debian::AptContents;

chdir; ## go to the home directory
my $c = Debian::AptContents->new({
    homedir => '.dh-make-perl',
    # verbose => 0,
});

unless (@ARGV) {
    @ARGV = qw(DateTime Perl::Critic::Bangs HTML::Parser);
}

my(@install_via_apt, @install_via_cpan);
for my $module (@ARGV) {
    if ( my $apt_package = $c->find_perl_module_package($module) ) {
            say "APT: $module: $apt_package";
            push @install_via_apt, $apt_package;
    } else {
            say "CPAN: $module";
            push @install_via_cpan, $module;
        }
}
print "\n";

say "aptitude install @install_via_apt" if @install_via_apt;
say "cpan @install_via_cpan" if @install_via_cpan;
