#!/bin/bash

# Get the FQDN of the host without making DNS queries.

domain=''
hostname=''

if [ -r /etc/hostname ]
then
    hostname="$(cat /etc/hostname)"
else
    hostname="$(hostname --short)"
fi

if [ -r /etc/resolv.conf ] && grep -q '^domain ' /etc/resolv.conf
then
    read -r _ domain < <(grep '^domain ' /etc/resolv.conf)

    if echo "${hostname}" | grep -q "${domain}$"; then
        echo "${hostname}"
    else
        echo "${hostname}.${domain}"
    fi
else
    echo "${hostname}"
fi
