#!/usr/bin/env bash
# Full disk test.

# SPDX-FileCopyrightText: 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

function main() {
    dev="$1"

    smartctl --test=short "$dev"
    sleep 200

    badblocks_and_secure_erase "$dev"

    # Give the disk some rest ;-)
    sleep 300
    hdparm -y "$dev" || :
    sleep 600

    smartctl --test=long "$dev"

    # Would require me knowing when the test finished.
    # Ref: disk-burnin-and-testing
    # hdparm -y
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]
then
    PS4='+ $(date --rfc-3339=seconds), ${BASH_SOURCE-}:${LINENO-}: '
    export PS4
    trap 'echo Encountered an unexpected error. Exiting with exit code $? in ${BASH_SOURCE-}:${LINENO-}. >&2' ERR
    set -o nounset -o pipefail -o errexit -o errtrace

    main "$@"
fi
