#!/bin/bash
# Adds your repo to the remotes of git. Useful when merging …

# SPDX-FileCopyrightText: 2015 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

git_remote_line="$(git remote --verbose | grep '^origin' | head --lines=1)"
if [ -z "$git_remote_line" ]; then
    git_remote_line="$(git remote --verbose | head --lines=1)"
fi
repo_name="$(echo "$git_remote_line" | perl -lne 'm#(?:(?<username>\w)/|://([^/]*/){2})(?<repo_name>[^ ]*?)(\.git| )# && print $+{repo_name}')"

echo "### Your repo is at: https://github.com/${GITHUB_USER}/${repo_name}"

if [ "$1" == '-p' ]; then
    git remote add my "${GITHUB_USER}.github.com:${GITHUB_USER}/${repo_name}.git"
    git push --set-upstream my
else
    echo 'Use -p for push.'
fi
