#!/bin/bash
if [ -z "$1" ]
then	echo "Please Enter a command for git like gc or fsck. This command will be executed on each git project found starting on the current working directory"
	exit 1
fi
find . -name ".git"|while read i;do e=${i%.git}; pushd "$e";git $1; popd >/dev/null;done
