#!/bin/bash
## Adds your repo to the remotes of git. Useful when merging …
##
## @licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
## @author Copyright (C) 2015 Robin Schneider <ypid@riseup.net>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, version 3 of the
## License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

repo_name="`git remote -v|grep '^origin'|head -n 1|sed 's/^.*\/\(.*\)\(\.git\| \).*/\1/'`"
git remote add my "${GITHUB_USER}.github.com:${GITHUB_USER}/${repo_name}.git"
echo "### Your repo is at: https://github.com/${GITHUB_USER}/${repo_name}"
git push --set-upstream my
