#!/bin/bash

# SPDX-FileCopyrightText: 2014 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

git log --show-signature --max-count=100 | grep 'RSA key' | sed 's/^.*using rsa key //i' | sort -u | while read -r keyID; do
    gpg --recv-keys "$keyID"
done
