#!/bin/bash
## Adds your repo to the remotes of git. Useful when merging …
##
## @licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
## @author Copyright (C) 2015 Robin Schneider <ypid@riseup.net>
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, version 3 of the
## License.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program.  If not, see <https://www.gnu.org/licenses/>.

git_remote_line="$(git remote --verbose | grep '^origin' | head --lines=1)"
if [ -z "$git_remote_line" ]; then
    git_remote_line="$(git remote --verbose | head --lines=1)"
fi
repo_name="$(echo "$git_remote_line" | perl -lne 'm#(?:(?<username>\w)/|://([^/]*/){2})(?<repo_name>[^ ]*?)(\.git| )# && print $+{repo_name}')"

echo "### Your repo is at: https://github.com/${GITHUB_USER}/${repo_name}"

if [ "$1" == '-p' ]; then
    git remote add my "${GITHUB_USER}.github.com:${GITHUB_USER}/${repo_name}.git"
    git push --set-upstream my
else
    echo 'Use -p for push.'
fi
