#!/usr/bin/env perl
use strict;
use warnings;
use autodie;
use feature qw(say);
use utf8;
use open qw(:std :utf8);
binmode STDOUT, ':encoding(UTF-8)';

my %lookup = (
    'ü' => '&uuml;',
    'Ü' => '&Uuml;',
    'ä' => '&auml;',
    'Ä' => '&Auml;',
    'ö' => '&ouml;',
    'Ö' => '&Ouml;',
    'ß' => '&szlig;',
    '>' => '&gt;',
    '<' => '&lt;',
);

my $reverse = 0;
if (defined $ARGV[0] and $ARGV[0] eq '-r') {
    shift @ARGV;
    $reverse = 1;
}

while (<>) {
    if ($reverse) {
        for my $key (keys %lookup) {
            s/$lookup{$key}/$key/g;
        }
        print;
    } else {
        for my $c (split(//, $_)) {
            if (exists $lookup{$c}) {
                print $lookup{$c}
            } else {
                print $c;
            }
        }
    }
}
