#!/bin/sh
#
BATTERY_DIR=/proc/acpi/battery/BAT0
log_file=$HOME/battery_low
#
if grep -q 'last full capacity' ${BATTERY_DIR}/info ; then
	FULL_BATTERY=$( awk '/last full capacity/ {print $4}' ${BATTERY_DIR}/info )
	CURRENT_BATTERY=$( awk '/remaining capacity/ {print $3}' ${BATTERY_DIR}/state )
	PERCENT=$(( ${CURRENT_BATTERY} * 100 / ${FULL_BATTERY} ))
	if ! on_ac_power
	then	date >> "$log_file"
		cat "${BATTERY_DIR}/info" "${BATTERY_DIR}/state" >> "$log_file"
		ping 192.168.0.1 -c 1 >> "$log_file"
		ip addr >> "$log_file"
		if [ "$PERCENT" -lt 23 ]
		then	echo "Akku $PERCENT% (Kritisch)" >> "$log_file"
			echo poweroff
		else	echo "Akku $PERCENT%" >> "$log_file"
		fi
#	else	echo "Netz $PERCENT%"
	fi
#else
#	echo "Ohne Akku"
fi

