#!/bin/bash
# Just a little script to create read only snapshots for the day. Can be executed from /etc/rc.local or something like that to start with a snapshot in case you screw up in the morning ;)

function for_subvol() {
   mkdir -p "$1/.snapshots"
   btrfs subvolume snapshot -r "$1" "$1/.snapshots/`date --iso`"
}

for_subvol '/home'
for_subvol '/'
