#!/bin/bash

## The exit status will be 0 if any NIC has an link state "up".

net_path="/sys/class/net"

for i in `ls -1 "$net_path"|grep -v "^lo$"`; do
    if [ "`cat "$net_path/$i/operstate"`" == "up" ]; then
        exit 0
	fi
done

exit 1
