#!/bin/bash

# SPDX-FileCopyrightText: 2016 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

for old_filename in ./*
do
    old_filename="${old_filename#./}"
    new_filename="$(crudini --get "$old_filename" connection id)"
    if [ "$old_filename" != "$new_filename" ]
    then
        mv "$old_filename" "$new_filename"
    fi
done
