#!/bin/bash
## @licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
## @author Copyright (C) 2015 Robin Schneider <ypid@riseup.net>
## It sets up a ssh Port forwarding, connects via telnet and enters the password
## for the remotekeyboard on Android. See: https://github.com/onyxbits/remotekeyboard
##
## The password is expected to be in the environment variable remotekeyboard.
## See also: https://github.com/onyxbits/remotekeyboard/issues/4#issuecomment-52207372

HOSTNAME="$1"
TELNET_PORT="2323"

if [ -z "$HOSTNAME" ]; then
    echo "Please enter the hostname of the device running ssh and remotekeyboard."
    exit 1
fi

# netstat -lnt | awk '$6 == "LISTEN" && $4 ~ ".2323"'
if ! nc -z localhost "$TELNET_PORT"; then
    if ! ssh -fNT -L$TELNET_PORT:localhost:$TELNET_PORT "$HOSTNAME"; then
        echo "Could not establish port forwarding via ssh."
        exit 1
    fi
fi

## https://github.com/ypid/scripts/blob/master/telnet-login
telnet-login --port $TELNET_PORT --password "$remotekeyboard" localhost
