#!/usr/bin/env perl
# Convert squid timestamp format to human readable format.
# Credits go to lavermil: http://www.linuxquestions.org/questions/linux-software-2/how-can-i-read-the-audit-time-stamp-msg%3Daudit-1213186256-105-20663-a-648547/
#
# Modified and maintained by Robin Schneider <ypid@riseup.net>
# @license AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

use strict;
use warnings;
use autodie;
use utf8;
use open qw(:std :utf8);
binmode STDOUT, ':encoding(UTF-8)';

while (<>) {
    if (/(?<time>\d+)\.\d+(?<post>.+)/xms) {
        my $human_readable_timestamp = scalar localtime $+{'time'};
        print "$human_readable_timestamp $+{'post'}";
    }
}
