#!/bin/bash

# SPDX-FileCopyrightText: 2018 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Fine-tuned ssh or sshrc wrapper which sets the terminal title to the ssh
# target and also resets the title when ssh terminates.

set -o nounset -o pipefail -o errexit

reset_terminal_title() {
    if [ "${TERM:-}" = "screen" ] && [ -n "${TMUX:-}" ]; then
        tmux set-window-option automatic-rename "on" 1>/dev/null
    else
        echo -ne '\033]0;Terminal\007'
    fi
}

# Simplified based on: https://github.com/Russell91/sshrc/blob/master/sshrc
get_ssh_cli_host() {
    while [[ -n "${1:-}" ]]; do
        case "${1:-}" in
            -*) ;;
             *) echo "${1:-}"; return 0 ;;
        esac
        shift
    done
    return 1
}


trap reset_terminal_title EXIT

ssh_command="${1:-ssh}"
shift

# https://gist.github.com/florianbeer/ee02c149a7e25f643491
if [ -z "$(get_ssh_cli_host "$@")" ]; then
    command "$ssh_command" "$@"
    exit 1
fi
if [ "${TERM:-}" = "screen" ] && [ -n "${TMUX:-}" ]; then
    tmux rename-window "$(get_ssh_cli_host "$@")"
    command "$ssh_command" "$@"
else
    echo -ne '\033]0;'"$(get_ssh_cli_host "$@")"'\007'
    command "$ssh_command" "$@"
fi
