#!/bin/bash
## Start rtorrent in the first tmux window if no user is logged in and stop rtorrent if one or more users are logged in.

log_file="$HOME/start_stop_rtorrent.log"

while true; do
    if pgrep "^rtorrent" 1>/dev/zero 2>&1; then
        if [[ `users | wc -w` != 0 ]]; then
            echo "`date`: Stopping rtorrent" >> "$log_file"
            killall --signal SIGINT rtorrent
        fi
    else
        if [[ `users | wc -w` == 0 ]]; then
            echo "`date`: Starting rtorrent" >> "$log_file"
            tmux send-keys -t:1 'rtorrent' Enter
        fi
    fi
    sleep 60
done
