#!/bin/bash
# Reverse of smount

# Copyright (C) 2017 Robin Schneider <ypid@riseup.net>
# SPDX-FileCopyrightText: 2017 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

set -o nounset -o pipefail -o errexit

name="${1:-}"
if [ -z "$name" ]; then
    echo 1>&2 "Please pass the device name as used in crypttab and fstab as first parameter."
    exit 1
fi

umount "/dev/mapper/$name"

# Get path of disk for spin-down at the end.
parent_device=""
if command -v lsblk >/dev/null 2>&1 && command -v hdparm >/dev/null 2>&1 && command -v jq >/dev/null 2>&1; then
    parent_device="$(lsblk "/dev/mapper/$name" --json --inverse --paths --output name | jq --raw-output '.blockdevices[0].children[0].name')"
fi

if cryptsetup status "$name"; then
    cryptdisks_stop "$name"
fi

# Attempt to spin-down the drive.
if [ -n "$parent_device" ]; then
    hdparm -y "$parent_device" || :
fi
