#!/bin/bash
# Reverse of smount

# Copyright (C) 2017 Robin Schneider <ypid@riseup.net>
# SPDX-FileCopyrightText: 2017 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

set -o nounset -o pipefail -o errexit

name="${1:-}"
if [ -z "$name" ]; then
    echo 1>&2 "Please pass the device name as used in crypttab and fstab as first parameter."
    exit 1
fi

if grep -q "^/dev/mapper/$name" /proc/mounts; then
    umount "/dev/mapper/$name"
fi
if cryptsetup status "$name"; then
    cryptdisks_stop "$name"
fi
