#!/usr/bin/python3
# -*- coding: utf-8 -*-

import string
import datetime
import logging

import pytz

LOG = logging.getLogger(__name__)


def strfdelta(tdelta, fmt='{D:02}d {H:02}h {M:02}m {S:02}s', inputtype='timedelta'):
    # Peace of awesomeness from: https://stackoverflow.com/questions/538666/format-timedelta-to-string/42320260#42320260
    """Convert a datetime.timedelta object or a regular number to a custom-
    formatted string, just like the stftime() method does for datetime.datetime
    objects.

    The fmt argument allows custom formatting to be specified.  Fields can
    include seconds, minutes, hours, days, and weeks.  Each field is optional.

    Some examples:
        '{D:02}d {H:02}h {M:02}m {S:02}s' --> '05d 08h 04m 02s' (default)
        '{W}w {D}d {H}:{M:02}:{S:02}'     --> '4w 5d 8:04:02'
        '{D:2}d {H:2}:{M:02}:{S:02}'      --> ' 5d  8:04:02'
        '{H}h {S}s'                       --> '72h 800s'

    The inputtype argument allows tdelta to be a regular number instead of the
    default, which is a datetime.timedelta object.  Valid inputtype strings:
        's', 'seconds',
        'm', 'minutes',
        'h', 'hours',
        'd', 'days',
        'w', 'weeks'
    """

    # Convert tdelta to integer seconds.
    if inputtype == 'timedelta':
        remainder = int(tdelta.total_seconds())
    elif inputtype in ['s', 'seconds']:
        remainder = int(tdelta)
    elif inputtype in ['m', 'minutes']:
        remainder = int(tdelta)*60
    elif inputtype in ['h', 'hours']:
        remainder = int(tdelta)*3600
    elif inputtype in ['d', 'days']:
        remainder = int(tdelta)*86400
    elif inputtype in ['w', 'weeks']:
        remainder = int(tdelta)*604800

    f = string.Formatter()
    desired_fields = [field_tuple[1] for field_tuple in f.parse(fmt)]
    possible_fields = ('W', 'D', 'H', 'M', 'S')
    constants = {'W': 604800, 'D': 86400, 'H': 3600, 'M': 60, 'S': 1}
    values = {}
    for field in possible_fields:
        if field in desired_fields and field in constants:
            values[field], remainder = divmod(remainder, constants[field])
    return f.format(fmt, **values)


ref_date = datetime.datetime(2023, 5, 23)

regex_map = {}

# Not supported on my system?
#  print(pytz.timezone("CST"))

for tz_name in pytz.all_timezones:
    #  if tz_name not in ['GMT']:
    #      continue

    tz = pytz.timezone(tz_name)

    try:
        utc_offset = tz.utcoffset(ref_date, is_dst=False)
    except Exception:
        utc_offset = tz.utcoffset(ref_date)

    utc_offset_str = strfdelta(utc_offset, "{H}:{M:02}")

    regex_map.setdefault(utc_offset_str, [])
    regex_map[utc_offset_str].append(tz_name)

print(regex_map)
