#!/bin/sh
# This OS dependent copy script was generated by https://github.com/ypid/scripts/blob/master/cdcat/cdcat.py.
# You will need to change the base path to the media "iceweasel" and the target path.

media_id_1=iceweasel
{} The copy script will create one directory for each media under "${target_path1}".

# Do not change the following commands. They can be regenerated be the script after altering the database with cdcat (in case you want to select other files as listed here).
robocopy "${media_id_1}/webapprt" "${target_path1}\webapprt" -s -r:2 -w:3 -log+:"target\log-%date:~6,4%-%date:~0,2%-%date:~3,2% _%time:~0,2%-%time:~3,2%-%time:~6,2%.log" -tee

