rem This OS dependent copy script was generated by https://github.com/ypid/scripts/blob/master/cdcat/cdcat.py.
rem Command line options used for the script: "../cdcat/copy_helper.py -s cmd no_selected_files.hcf"
rem You will need to change the base path to the media "iceweasel" and the target path.

rem Path to the base directory of the media (same as the one selected in cdcat for this media).

set target_path=d:\external_disk\

rem Do not change the following commands. They can be regenerated be the script after altering the database with cdcat (in case you want to select other files as listed here).
pause

