rem This OS dependent copy script was generated by https://github.com/ypid/scripts/blob/master/cdcat/cdcat.py.
rem Command line options used for the script: "../cdcat/copy_helper.py -m robocopy files_selected.hcf -s cmd"
rem You will need to change the base path to the media "iceweasel" and the target path.

set media_id_1=iceweasel
set target_path=d:\external_disk\
{} The copy script will create one directory for each media under "%target_path1%".

rem Do not change the following commands. They can be regenerated be the script after altering the database with cdcat (in case you want to select other files as listed here).
robocopy "%media_id_1%/webapprt" "%target_path1%\webapprt" -s -r:2 -w:3 -log+:"target\log-%date:~6,4%-%date:~0,2%-%date:~3,2% _%time:~0,2%-%time:~3,2%-%time:~6,2%.log" -tee
pause

