#!/bin/sh
# This OS dependent copy script was generated by https://github.com/ypid/scripts/blob/master/cdcat/cdcat.py.
# You will need to change the base path to the media "icedove" and the target path.

media_id_2=icedove
{} The copy script will create one directory for each media under "${target_path2}".

# Do not change the following commands. They can be regenerated be the script after altering the database with cdcat (in case you want to select other files as listed here).
robocopy "${media_id_2}/chrome/icons/default/default24.png" "${target_path2}\chrome/icons/default" -s -r:2 -w:3 -log+:"target\log-%date:~6,4%-%date:~0,2%-%date:~3,2% _%time:~0,2%-%time:~3,2%-%time:~6,2%.log" -tee
robocopy "${media_id_2}/defaults/pref" "${target_path2}\defaults/pref" -s -r:2 -w:3 -log+:"target\log-%date:~6,4%-%date:~0,2%-%date:~3,2% _%time:~0,2%-%time:~3,2%-%time:~6,2%.log" -tee
robocopy "${media_id_2}/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}" "${target_path2}\extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}" -s -r:2 -w:3 -log+:"target\log-%date:~6,4%-%date:~0,2%-%date:~3,2% _%time:~0,2%-%time:~3,2%-%time:~6,2%.log" -tee

