#!/usr/bin/env perl

# SPDX-FileCopyrightText: 2013 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

use strict;
use warnings;
use autodie;
use feature qw(say);
use utf8;
binmode STDOUT, ':encoding(UTF-8)';
use File::Path;

my $HOME              = $ENV{'HOME'};
my $podcasts          = "$HOME/podcasts";
my $podcasts_familiar = "$HOME/podcasts_familiar";
push @ARGV, qw( /var/log/nginx/access.log /var/log/nginx/access.log.1 ) unless @ARGV;
while (<>) {
    next unless m#podcasts/.*mp3.*Nokia#xms;
    my ( $podname, $file ) = ( split /\//xms, (split)[6] )[ -2, -1 ];
    my $cur_file = "$podcasts/$podname/$file";
    if ( -e $cur_file ) {
        my $new_pod_dir = "$podcasts_familiar/$podname";
        say "$cur_file -> $new_pod_dir/$file";
        mkpath $new_pod_dir;
        rename $cur_file, "$podcasts_familiar/$podname/$file";
    }
}
