#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# SPDX-FileCopyrightText: 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Hello world Nagios check."""

from __future__ import (print_function, unicode_literals,
                        absolute_import, division)

import argparse
import logging

import nagiosplugin

__version__ = '0.1.0'
_LOG = logging.getLogger(__name__)


class TODOres(nagiosplugin.Resource):

    def __init__(self, filename):
        self._filename = filename

    def probe(self):
        _LOG.debug('Reading file: {}'.format(self._filename))
        my_value = 0
        yield nagiosplugin.Metric(
            'water level'.format(self._filename),
            my_value,
            min=0,
            uom='m')


@nagiosplugin.guarded
def main():
    args_parser = argparse.ArgumentParser(description=__doc__)
    args_parser.add_argument('-w', '--warning', metavar='RANGE', default='')
    args_parser.add_argument('-c', '--critical', metavar='RANGE', default='')
    args_parser.add_argument('-f', '--filename', required=True)
    args_parser.add_argument('-v', '--verbose', action='count', default=0)
    args_parser.add_argument(
        '-V', '--version', action='version',
        version='%(prog)s {}'.format(__version__))
    cli_args = args_parser.parse_args()
    logging.basicConfig(
        format='%(levelname)s %(asctime)s (%(filename)s:%(lineno)s) %(message)s', datefmt="%a %F %T%z",
        level={0: logging.WARNING, 1: logging.WARNING, 2: logging.INFO}.get(
            cli_args.verbose, logging.DEBUG))

    check = nagiosplugin.Check(
        TODOres(cli_args.filename),
        nagiosplugin.ScalarContext('water level', cli_args.warning, cli_args.critical))
    check.main(verbose=cli_args.verbose)


if __name__ == '__main__':
    main()
