#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2018 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

set -o nounset -o pipefail -o errexit

if [ "$#" -ne 1 ]; then
    echo "Call as: ./$0 <base_path>"
fi

base_path="${1}"

# shellcheck disable=SC2016
rmlint "$base_path" -c 'sh:cmd=ln -srf $2 $1' -o sh:rmlint.sh
./rmlint.sh -q -d
