#!/bin/sh

# SPDX-FileCopyrightText: 2017 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-only

filename="$1"

if [ -z "$filename" ]
then
	echo "You need to specify the section to restore." 1>&2
	exit 1
fi

db_location="/$(echo "${filename%.dump}" | tr '.' '/')/"
dconf load "$db_location" < "$filename"
